#!/bin/bash

export LC_ALL=en_US.UTF-8

chef-client \
    -l info \
    -L /var/log/chef/client.log \
    >/dev/null 2>&1

if [ "$?" == "0" ]; then
    echo 'ok'   >/var/log/chef/last_run_status
else
    echo 'failed' >/var/log/chef/last_run_status
fi

chmod 640 /var/log/chef/client.log
chmod 644 /var/log/chef/last_run_status
