#! /bin/sh
# update-rc.d is handled by the recipe
#
# unregister-chef         Chef un-register script
# chkconfig: - 2345 99 01
# description: Unregister chef client from server on shutdown

NAME=unregister-chef

stop() {
  /opt/chef/bin/unregister_chef
}

start() {
  true
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop}" >&2
    exit 1
    ;;
esac

exit 0
